language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "JYPmYQZyP8r/S0vYByCHij23kaWc4H0cj7dH8HNH8SPYxj7BaAAAME0CHEXhRCW++LaNOwgWalbgyFJDsitwrXbYVfqCfTmIHq9nwzvqtWv64jPHU78r1BYKuVyXjAdVez2XwPyC37QOEOXTDKh6tMtr77GyjJg1Ic8GjINHBPJdBGGwZz2aaZjdHgFxZmMp7zEr+kN+c1Gok3bJ8lWuREtURczBX+tyLiHysYUm78bkSfVlo7zHJBVvV7jJIrfFxhnGOQK5Y/AQIFidLE511N5Uyollfada3zlvCTjqG+0YDaAlVQUjy4KOE2VhVmeF+RiK3j5Mp4wW2OM07ByVq2rdlUY7c7uOKSh2oETxbRh0pBMOovqnVRoGGqER/Je4+mpKy2gAh7Hi34pl4F9pVHmUrfmiQxH0GKN1Er/a2VqoH1DVmIexY84TQk6vV/ON1otLBOWYkx4xopqrmwlXpxN2OB7RH9ZeSNBBo4jihUW7nerNBNgXOTJX54Oqhz3K1RXQfYxmQVQc69ed4D06b/WoZDzj3BIn/ytItDiZFnb6MfQtkNYehEXljKHsAhtt5uVQszc3agBYHAtlQ4mzZwWS1eQNqDJ4O1eIjtVYgO77kyWbP78m01AefymkDKbVTI1m8awWHR05yGneI4hg33XGAR8RWvrlkgrBIAxuZ20="
  api_key: # d015
    secure: "qrfsXP+KuGweoDx8kKx/OYMJB9yIQrm3fWaJDgj/Vz8qbSrCL5RkHueQC92lK2n+CHQFBP3aV3/jFtyvmVoeFLjbkerekgjyTjT1/0PGEFgumKgBwwLckHzeY2JIv8chnydbrUZLFDHME4i/cR8qze7FX/ELlIDrPl2yysXGCOIglKozCkA2/J1ZiVVKi6vKXrqyEVZN5hiKiqp2FaTu3EEQ3vleIuGBERpX5jNmsWRqa2BHbjEJAKSUXKjVmXqqr+tN8gYzZ9rYTBJSJilZS19lrYfIRGfp9cBWEi7n2qbV85AklYk+tbeWa/DL55ypNj0u2oY+MaGAURZEl9lAj5cXVcIplYhQJLg34Gxuq2DHxShv4NS84lRFMnHzu43d/xqB2BpwVLzsTV9PCLQjA2wZWFEWZb3KgoouEhorjuaMjayS3htDu2NpuMg+sXN0trThdO3YQOWEyw794oyk9V8XZ6e0SeSAihHXUxwSzzMkKolNAF7zRCY/XjSEBP7/V49gRQiN9PvaviozZJj0rf4nQ1l8uveN5eTv0g6WVOKVWnX+a0ZgmU4YUtIk4AuF4w1M/er2JSaJ65qfgygxOpeeEbfK1+dGCntnITim76pvjO9lwagV41SnY1I2AAlky3BDhLCe0n0dGTI+gz/Ki8pnoBj2Gzvc1AkpdyJZWes="
  on:
    tags: true
    node: lts/*
